version: '3'

services:
  php:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/php-fpm:7.3'
    ports:
      - 9000:9000
    volumes:
      - .:/app